language: python
python:
  - "2.7"
before_script:
  - echo -e "[TESTING] This is executed on BEFORE_SCRIPT"
script:
  - echo -e "[TESTING] This is executed on SCRIPT"
after_success:
  - echo "[TESTING] This is executed on AFTER_SUCCESS"
after_failure:
  - echo "[TESTING] This is executed on AFTER_FAILURE"
before_deploy:
  - echo "[TESTING] This is executed on BEFORE_DEPLOY"
after_deploy:
  - echo "[TESTING] This is executed on DEPLOY"
after_script:
  - echo "[TESTING] This is executed on AFTER_SCRIPT"
